#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-here
Version  : 1.0.1
Release  : 22
URL      : https://cran.r-project.org/src/contrib/here_1.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/here_1.0.1.tar.gz
Summary  : A Simpler Way to Find Your Files
Group    : Development/Tools
License  : MIT
Requires: R-rprojroot
BuildRequires : R-rprojroot
BuildRequires : buildreq-R

%description
Declare the relative path of a file within your project with 'i_am()'.
    Use the 'here()' function as a drop-in replacement for 'file.path()',
    it will always locate the files relative to your project root.

%prep
%setup -q -c -n here
cd %{_builddir}/here

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1608160385

%install
export SOURCE_DATE_EPOCH=1608160385
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library here
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library here
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library here
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc here || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/here/DESCRIPTION
/usr/lib64/R/library/here/INDEX
/usr/lib64/R/library/here/LICENSE
/usr/lib64/R/library/here/Meta/Rd.rds
/usr/lib64/R/library/here/Meta/features.rds
/usr/lib64/R/library/here/Meta/hsearch.rds
/usr/lib64/R/library/here/Meta/links.rds
/usr/lib64/R/library/here/Meta/nsInfo.rds
/usr/lib64/R/library/here/Meta/package.rds
/usr/lib64/R/library/here/Meta/vignette.rds
/usr/lib64/R/library/here/NAMESPACE
/usr/lib64/R/library/here/NEWS.md
/usr/lib64/R/library/here/R/here
/usr/lib64/R/library/here/R/here.rdb
/usr/lib64/R/library/here/R/here.rdx
/usr/lib64/R/library/here/WORDLIST
/usr/lib64/R/library/here/demo-project/analysis/report.Rmd
/usr/lib64/R/library/here/demo-project/data/penguins.csv
/usr/lib64/R/library/here/demo-project/demo-project.Rproj
/usr/lib64/R/library/here/demo-project/prepare/penguins.R
/usr/lib64/R/library/here/doc/here.R
/usr/lib64/R/library/here/doc/here.Rmd
/usr/lib64/R/library/here/doc/here.html
/usr/lib64/R/library/here/doc/index.html
/usr/lib64/R/library/here/doc/rmarkdown.R
/usr/lib64/R/library/here/doc/rmarkdown.Rmd
/usr/lib64/R/library/here/doc/rmarkdown.html
/usr/lib64/R/library/here/help/AnIndex
/usr/lib64/R/library/here/help/aliases.rds
/usr/lib64/R/library/here/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/here/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/here/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/here/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/here/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/here/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/here/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/here/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/here/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/here/help/here.rdb
/usr/lib64/R/library/here/help/here.rdx
/usr/lib64/R/library/here/help/paths.rds
/usr/lib64/R/library/here/html/00Index.html
/usr/lib64/R/library/here/html/R.css
/usr/lib64/R/library/here/tests/testthat.R
/usr/lib64/R/library/here/tests/testthat/_snaps/dr_here.md
/usr/lib64/R/library/here/tests/testthat/_snaps/i_am.md
/usr/lib64/R/library/here/tests/testthat/helper-expect.R
/usr/lib64/R/library/here/tests/testthat/helper-local.R
/usr/lib64/R/library/here/tests/testthat/setup.R
/usr/lib64/R/library/here/tests/testthat/test-dr_here.R
/usr/lib64/R/library/here/tests/testthat/test-here.R
/usr/lib64/R/library/here/tests/testthat/test-i_am.R
/usr/lib64/R/library/here/tests/testthat/test-set_here.R
